// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nhjodtpylsnbazuipwvc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5oam9kdHB5bHNuYmF6dWlwd3ZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxODIyOTEsImV4cCI6MjA2Mzc1ODI5MX0.uc04MX8RCDBX91CBWQhU_TK_wAXS0Nf88hpyZ-aUR9A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);